codecov:
  require_ci_to_pass: true

ai_pr_review:
  enabled: false

coverage:
  precision: 2
  round: down
  range: '90...100'

  status:
    project: yes
    patch: true
    changes: false

github_checks:
  annotations: false